### ISSUE TITLE
Nothing happens :-( 

### ISSUE THREAD

**Issue by jegjessing** [Digilent/Arty-A7-100-XADC#2]
I'm trying to get into this FPGA / ADC thingy :-) and was thinking that this was a good starting point.

I have some problems though. I opened the project as described in the README.
Vivado informed that it was out of date and updated it. Also the IP was updated, no complaints.

I built it just fine and ran program device, no problem.
All switches are set to 0, I've connected my function generator with a 1Hz 500mVpp to XGND and A0.
I was expecting some sort of output on the LED's. But nothing happens :-( Any suggestions on how to debug?

I have uploaded and been running other things, like switch -> LED, blinking with different frequency etc just fine.
Makes me suspect the IP not being 100% correctly converted?

**Comment by jegjessing** [comment]
Just want to add. I have of course, tried a various combinations of analog inputs and SW combinations :-(

**Comment by artvvb** [comment]
There are a couple of different issues that could be occurring, which are addressed in this thread on our forum: https://forum.digilent.com/topic/24843-xadc-in-arty-a7-100t/#comment-73826

First, if the switches start out in or are moved to a state greater than 0x8 (eg switches 3 and 0 up, the others down), conversion will stop and the board has to be reprogrammed to continue.

Second, the input voltage divider used to scale signals down from 3.3 V to 1 V at the XADC input might not be playing well with your function generator (less likely in this case).

Not sure what version of Vivado you're using, but the first issue is corrected in the 2022.1-2 release of the demo (which has since been migrated to another repo), which can be found here: https://digilent.com/reference/programmable-logic/arty-a7/demos/xadc.

**Comment by jegjessing** [comment]
Looks like the conversion from this project to version 2022.2 was the issue.
I don't know how I ended up in this old project. I tried the code in new repo and voila. Thanks
